## Input options
input                               = null
platform                            = null

## References
genome                              = null
genome_fasta                        = null
transcript_fasta                    = null
gtf                                 = null
igenomes_base                       = 's3://ngi-igenomes/igenomes/'
igenomes_ignore                     = true
fasta_delimiter                     = ""

## Fastq Options
split_amount                        = 0

## Read Trimming Options
min_length                          = 1
min_q_score                         = 10
skip_trimming                       = false

## Cell barcode options
whitelist                           = null
barcode_format                      = null
dedup_tool                          = 'umitools'

## Parse related options
parse_generate_pe                   = "--chemistry v3 --l1dist 3 --l2dist 2"
parse_spipe                         = "--chemistry v3 --kit WT_mini"

## Library strandness option
stranded                            = null

## Mapping
skip_save_minimap2_index            = false
kmer_size                           = 14

## Analysis options
retain_introns                      = true
quantifier                          = ''
